// Generated by gencpp from file dynamixel_control/GetPosition.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROL_MESSAGE_GETPOSITION_H
#define DYNAMIXEL_CONTROL_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <dynamixel_control/GetPositionRequest.h>
#include <dynamixel_control/GetPositionResponse.h>


namespace dynamixel_control
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace dynamixel_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_control::GetPosition > {
  static const char* value()
  {
    return "954ac3955681827bc0e9997911512d36";
  }

  static const char* value(const ::dynamixel_control::GetPosition&) { return value(); }
};

template<>
struct DataType< ::dynamixel_control::GetPosition > {
  static const char* value()
  {
    return "dynamixel_control/GetPosition";
  }

  static const char* value(const ::dynamixel_control::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_control::GetPositionRequest> should match
// service_traits::MD5Sum< ::dynamixel_control::GetPosition >
template<>
struct MD5Sum< ::dynamixel_control::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_control::GetPosition >::value();
  }
  static const char* value(const ::dynamixel_control::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_control::GetPositionRequest> should match
// service_traits::DataType< ::dynamixel_control::GetPosition >
template<>
struct DataType< ::dynamixel_control::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_control::GetPosition >::value();
  }
  static const char* value(const ::dynamixel_control::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_control::GetPositionResponse> should match
// service_traits::MD5Sum< ::dynamixel_control::GetPosition >
template<>
struct MD5Sum< ::dynamixel_control::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_control::GetPosition >::value();
  }
  static const char* value(const ::dynamixel_control::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_control::GetPositionResponse> should match
// service_traits::DataType< ::dynamixel_control::GetPosition >
template<>
struct DataType< ::dynamixel_control::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_control::GetPosition >::value();
  }
  static const char* value(const ::dynamixel_control::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CONTROL_MESSAGE_GETPOSITION_H
