// Generated by gencpp from file dynamixel_control/GetPositionRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROL_MESSAGE_GETPOSITIONREQUEST_H
#define DYNAMIXEL_CONTROL_MESSAGE_GETPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_control
{
template <class ContainerAllocator>
struct GetPositionRequest_
{
  typedef GetPositionRequest_<ContainerAllocator> Type;

  GetPositionRequest_()
    : id(0)  {
    }
  GetPositionRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionRequest_

typedef ::dynamixel_control::GetPositionRequest_<std::allocator<void> > GetPositionRequest;

typedef boost::shared_ptr< ::dynamixel_control::GetPositionRequest > GetPositionRequestPtr;
typedef boost::shared_ptr< ::dynamixel_control::GetPositionRequest const> GetPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_control::GetPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_control::GetPositionRequest_<ContainerAllocator1> & lhs, const ::dynamixel_control::GetPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_control::GetPositionRequest_<ContainerAllocator1> & lhs, const ::dynamixel_control::GetPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::dynamixel_control::GetPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_control/GetPositionRequest";
  }

  static const char* value(const ::dynamixel_control::GetPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
;
  }

  static const char* value(const ::dynamixel_control::GetPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_control::GetPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_control::GetPositionRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_CONTROL_MESSAGE_GETPOSITIONREQUEST_H
