// Generated by gencpp from file dynamixel_control/SetPosition.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CONTROL_MESSAGE_SETPOSITION_H
#define DYNAMIXEL_CONTROL_MESSAGE_SETPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_control
{
template <class ContainerAllocator>
struct SetPosition_
{
  typedef SetPosition_<ContainerAllocator> Type;

  SetPosition_()
    : id(0)
    , position(0)  {
    }
  SetPosition_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::dynamixel_control::SetPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_control::SetPosition_<ContainerAllocator> const> ConstPtr;

}; // struct SetPosition_

typedef ::dynamixel_control::SetPosition_<std::allocator<void> > SetPosition;

typedef boost::shared_ptr< ::dynamixel_control::SetPosition > SetPositionPtr;
typedef boost::shared_ptr< ::dynamixel_control::SetPosition const> SetPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_control::SetPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_control::SetPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_control::SetPosition_<ContainerAllocator1> & lhs, const ::dynamixel_control::SetPosition_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_control::SetPosition_<ContainerAllocator1> & lhs, const ::dynamixel_control::SetPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_control::SetPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_control::SetPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_control::SetPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_control::SetPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_control::SetPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_control::SetPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_control::SetPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "833110e1050ad82a9398ab64153a6a86";
  }

  static const char* value(const ::dynamixel_control::SetPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x833110e1050ad82aULL;
  static const uint64_t static_value2 = 0x9398ab64153a6a86ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_control::SetPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_control/SetPosition";
  }

  static const char* value(const ::dynamixel_control::SetPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_control::SetPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int32 position\n"
;
  }

  static const char* value(const ::dynamixel_control::SetPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_control::SetPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_control::SetPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_control::SetPosition_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_CONTROL_MESSAGE_SETPOSITION_H
